apiVersion: v1
kind: Secret
metadata:
  name: {{ include "python-backend.fullname" . }}
  labels:
    {{- include "python-backend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
